collision_clearance: 0.005

collision_links:
  robot_platform_link
  base_link
  link_2
  robotiq_palm
  link_3
  link_6
  link_1
  link_5
  tcp_frame
  tool0
  link_4
  robotiq_finger_1
  robotiq_finger_2
  robotiq_finger_3
  window_frame
  bottom_link
  left_link
  right_link
  top_link

joint_costs:
  joint_1: 1.0
  joint_1: 1.0
  joint_1: 1.0
  joint_1: 1.0
  joint_1: 1.0
  joint_1: 1.0

joint_velocity_limits:
  joint_1: 2.8
  joint_2: 2.8
  joint_3: 3.0
  joint_4: 6.1
  joint_5: 5.9
  joint_6: 9.0

reference_frame: world_frame

collision_space:
  size_x: 4.0
  size_y: 4.0
  size_z: 4.0
  origin_x: 0.0
  origin_y: 0.0
  origin_z: 0.0
  resolution: 0.02
  field_bias_x: 0.0
  field_bias_y: 0.0
  field_bias_z: 0.0
      
chomp_collision_operations:
  - object1: world_frame
    object2: robot_platform_link
    operation: disable  # Adjacent in collision
  - object1: robot_platform_link
    object2: base_link
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: link_1
    operation: disable  # Adjacent in collision
  - object1: link_1
    object2: link_2
    operation: disable  # Adjacent in collision
  - object1: link_2
    object2: link_3
    operation: disable  # Adjacent in collision
  - object1: link_3
    object2: link_4
    operation: disable  # Adjacent in collision
  - object1: link_4
    object2: link_5
    operation: disable  # Adjacent in collision
  - object1: link_5
    object2: link_6
    operation: disable  # Adjacent in collision
  - object1: link_6
    object2: tool0
    operation: disable  # Adjacent in collision
  - object1: tool0
    object2: robotiq_palm
    operation: disable  # Adjacent in collision
  - object1: robotiq_palm
    object2: tcp_frame
    operation: disable  # Adjacent in collision
  - object1: robotiq_palm
    object2: robotiq_finger_1
    operation: disable  # Adjacent in collision
  - object1: robotiq_palm
    object2: robotiq_finger_2
    operation: disable  # Adjacent in collision
  - object1: robotiq_palm
    object2: robotiq_finger_3
    operation: disable  # Adjacent in collision
  - object1: world_frame
    object2: window_frame
    operation: disable  # Adjacent in collision
  - object1: window_frame
    object2: bottom_link
    operation: disable  # Adjacent in collision
  - object1: window_frame
    object2: left_link
    operation: disable  # Adjacent in collision
  - object1: window_frame
    object2: right_link
    operation: disable  # Adjacent in collision
  - object1: window_frame
    object2: top_link
    operation: disable  # Adjacent in collision
  - object1: bottom_link
    object2: left_link
    operation: disable  # Always in collision
  - object1: bottom_link
    object2: right_link
    operation: disable  # Always in collision
  - object1: left_link
    object2: top_link
    operation: disable  # Always in collision
  - object1: right_link
    object2: top_link
    operation: disable  # Always in collision
  - object1: base_link
    object2: bottom_link
    operation: disable  # Never in collision
  - object1: base_link
    object2: left_link
    operation: disable  # Never in collision
  - object1: base_link
    object2: link_3
    operation: disable  # Never in collision
  - object1: base_link
    object2: right_link
    operation: disable  # Never in collision
  - object1: base_link
    object2: top_link
    operation: disable  # Never in collision
  - object1: bottom_link
    object2: link_1
    operation: disable  # Never in collision
  - object1: bottom_link
    object2: link_2
    operation: disable  # Never in collision
  - object1: bottom_link
    object2: link_3
    operation: disable  # Never in collision
  - object1: bottom_link
    object2: robot_platform_link
    operation: disable  # Never in collision
  - object1: bottom_link
    object2: top_link
    operation: disable  # Never in collision
  - object1: left_link
    object2: link_1
    operation: disable  # Never in collision
  - object1: left_link
    object2: link_2
    operation: disable  # Never in collision
  - object1: left_link
    object2: link_3
    operation: disable  # Never in collision
  - object1: left_link
    object2: right_link
    operation: disable  # Never in collision
  - object1: left_link
    object2: robot_platform_link
    operation: disable  # Never in collision
  - object1: link_1
    object2: link_3
    operation: disable  # Never in collision
  - object1: link_1
    object2: right_link
    operation: disable  # Never in collision
  - object1: link_1
    object2: robot_platform_link
    operation: disable  # Never in collision
  - object1: link_1
    object2: top_link
    operation: disable  # Never in collision
  - object1: link_2
    object2: right_link
    operation: disable  # Never in collision
  - object1: link_2
    object2: top_link
    operation: disable  # Never in collision
  - object1: link_3
    object2: link_5
    operation: disable  # Never in collision
  - object1: link_3
    object2: link_6
    operation: disable  # Never in collision
  - object1: link_3
    object2: right_link
    operation: disable  # Never in collision
  - object1: link_3
    object2: robotiq_finger_1
    operation: disable  # Never in collision
  - object1: link_3
    object2: robotiq_finger_2
    operation: disable  # Never in collision
  - object1: link_3
    object2: robotiq_finger_3
    operation: disable  # Never in collision
  - object1: link_3
    object2: robotiq_palm
  - object1: link_4
    object2: robotiq_palm
    operation: disable  # Never in collision
  - object1: link_3
    object2: top_link
    operation: disable  # Never in collision
  - object1: link_4
    object2: robotiq_finger_1
    operation: disable  # Never in collision
  - object1: link_4
    object2: robotiq_finger_2
    operation: disable  # Never in collision
  - object1: link_4
    object2: robotiq_finger_3
    operation: disable  # Never in collision
  - object1: link_5
    object2: robotiq_finger_1
    operation: disable  # Never in collision
  - object1: link_5
    object2: robotiq_finger_2
    operation: disable  # Never in collision
  - object1: link_5
    object2: robotiq_finger_3
    operation: disable  # Never in collision
  - object1: link_5
    object2: robotiq_palm
    operation: disable  # Never in collision
  - object1: link_6
    object2: robotiq_finger_1
    operation: disable  # Never in collision
  - object1: link_6
    object2: robotiq_finger_2
    operation: disable  # Never in collision
  - object1: link_6
    object2: robotiq_finger_3
    operation: disable  # Never in collision
  - object1: link_6
    object2: robotiq_palm
    operation: disable  # Never in collision
  - object1: right_link
    object2: robot_platform_link
    operation: disable  # Never in collision
  - object1: robot_platform_link
    object2: top_link
    operation: disable  # Never in collision
  - object1: robotiq_finger_1
    object2: robotiq_finger_2
    operation: disable  # Never in collision
  - object1: robotiq_finger_1
    object2: robotiq_finger_3
    operation: disable  # Never in collision
  - object1: robotiq_finger_2
    object2: robotiq_finger_3
    operation: disable  # Never in collision
