joint_limits:
  Joint_1:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.8
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  Joint_2:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.8
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  Joint_3:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  Joint_4:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 6.1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  Joint_5:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 5.9
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  Joint_6:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 9
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false