joint_trajectory_action:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  constraints:
    goal_time: 2.0
    joint_1:
      goal: 0.04
    joint_2:
      goal: 0.04
    joint_3:
      goal: 0.04
    joint_4:
      goal: 0.04
    joint_5:
      goal: 0.04
    joint_6:
      goal: 0.04
