cartesian_trajectory:
  arm_group: manipulator
  frame_id: base_link
  link_name: Link_6
  via_points:
    - position:
        x: 1.2
        y: 0.24
        z: 0.6
      orientation:
        axis:
          x: -1.0
          y: 0.0
          z: 0.0
        angle: 0.01
    - position:
        x: 1.2
        y: -0.24
        z: 0.6
      orientation:
        axis:
          x: -1.0
          y: 0.0
          z: 0.0
        angle: 0.01
