# ROS to MTConnect Conversion Data File
#
# For use with the ROS action client: mtconnect_action_server.py
#
# User enters a ROS action and the conversion between
# the action result and the MTConnect CNC State Tag:
#
# ROS action:
#     {ROS action result1:XML_state1, ROS action result2:XML_state2, ...}
#
# The ROS publisher will convert this data into the following dictionary:
# {MaterialUnload: {'UNLOADING':'ACTIVE', 'UNLOADED':'COMPLETE', 'READY':'READY'}}
#----------------------------------------------------------- 
# Enter the ROS action and the MTConnect XML conversion below:

MaterialLoad:
    {'LOADING':'ACTIVE', 'LOADED':'COMPLETE', 'READY':'READY'}
MaterialUnload:
    {'UNLOADING':'ACTIVE', 'UNLOADED':'COMPLETE', 'READY':'READY'}
DoorAcknowledge:
    {'ACK':'ACTIVE', 'READY':'READY'}
ChuckAcknowledge:
    {'ACK':'ACTIVE', 'READY':'READY'}