url: 'localhost'
url_port: 5000
machine_tool: '/cnc'
xml_namespace: 'urn:mtconnect.org:MTConnectStreams:1.2'
adapter_port: 7886

mtconnect_msgs:
    OpenDoor:
        sequence:
            {'ACTIVE': 'ACTIVE', 'COMPLETE' : 'COMPLETE', 'READY' : 'READY'}
    CloseDoor:
        sequence:
            {'ACTIVE': 'ACTIVE', 'COMPLETE' : 'COMPLETE', 'READY' : 'READY'}
    OpenChuck:
        sequence:
            {'ACTIVE': 'ACTIVE', 'COMPLETE' : 'COMPLETE', 'READY' : 'READY'}
    CloseChuck:
        sequence:
            {'ACTIVE': 'ACTIVE', 'COMPLETE' : 'COMPLETE', 'READY' : 'READY'}
