# MTConnect to ROS Conversion Data File
#
# For use with the ROS publisher: bridge_publisher.py
#
# The format for the .yaml file:
# 
# URL: Port Number
#
# ROS Topic Name (arbitrary)
#     ROS Topic Type Class in relative format: namespace/type
#         MTConnect Data Item (must match XML tag.attrib['name']
#             MTConnect Data Item Text to ROS Message CONSTANT conversion
#
# User enters MTConnect Data Item text and the conversion between
# the data item text and the ROS message CONSTANT:
#
# XML Data Item Name:
#     {xml_state1:ROS_CONSTANT1, xml_state2:ROS_CONSTANT2, ...}
#
# The ROS publisher will convert this data into the following dictionary:
# {key_port: val_port, key_topic_name: {keyval_topic_type : {keyval_dataitem : {key_di_name : val_ROS_CONSTANT}}}}
#
# For example:
# {'localhost': 5000, 'CncReponseTopic': {'mtconnect_msgs/CncStatus':
#     {'open_door': {'ACTIVE': 'ENABLED', 'READY': 'OPEN', 'NOT READY': 'OFF',
#                    'UNAVAILABLE': 'UNKNOWN', 'COMPLETE': 'TRUE'}}}}
#----------------------------------------------------------- 

localhost: 5000

CncResponseTopic:
    mtconnect_msgs/CncStatus:
        open_door:
            {'ACTIVE':'ENABLED','COMPLETE':'TRUE','READY':'OPEN', 'NOT READY':'OFF', 'UNAVAILABLE':'UNKNOWN'}
        close_door:
            {'ACTIVE':'ENABLED','COMPLETE':'TRUE','READY':'OPEN', 'NOT READY':'OFF', 'UNAVAILABLE':'UNKNOWN'}
        door_state:
            {'OPEN':'OPEN','CLOSED':'CLOSED','UNLATCHED':'UNKNOWN', 'NOT READY':'UNKNOWN', 'UNAVAILABLE':'UNKNOWN'}
        open_chuck:
            {'ACTIVE':'ENABLED','COMPLETE':'TRUE','READY':'OPEN', 'NOT READY':'OFF', 'UNAVAILABLE':'UNKNOWN'}
        close_chuck:
            {'ACTIVE':'ENABLED','COMPLETE':'TRUE','READY':'OPEN', 'NOT READY':'OFF', 'UNAVAILABLE':'UNKNOWN'}
        chuck_state:
            {'OPEN':'OPEN','CLOSED':'CLOSED','UNLATCHED':'UNKNOWN', 'NOT READY':'UNKNOWN', 'UNAVAILABLE':'UNKNOWN'}

CncRequestTopic:
    mtconnect_msgs/CncRequest:
        material_load:
            {'ACTIVE':'ENABLED','COMPLETE':'TRUE','READY':'OPEN', 'NOT READY':'OFF', 'UNAVAILABLE':'UNKNOWN'}
        material_unload:
            {'ACTIVE':'ENABLED','COMPLETE':'TRUE','READY':'OPEN', 'NOT READY':'OFF', 'UNAVAILABLE':'UNKNOWN'}